dex:
  connectors:
    github:
      config:
        clientID: vault:gitOps/Bootstrap-Jersey/environment-d68-dev/dex-connectors-github-config:clientID
        clientSecret: vault:gitOps/Bootstrap-Jersey/environment-d68-dev/dex-connectors-github-config:clientSecret
        name: GitHub
        type: github
  domain: kill-9.uk
enabledConnector: GitHub
